// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Floresta",
    platforms: [
        .iOS(.v15),
        .macOS(.v13),
    ],
    products: [
        .library(
            name: "Floresta",
            targets: ["Floresta"]
        ),
    ],
    targets: [
        // XCFramework hosted on GitHub Releases.
        // After pushing a release, set the url to the release asset URL and
        // update the checksum by running:
        //   swift package compute-checksum florestaFFI.xcframework.zip
                .binaryTarget(
            name: "florestaFFI",
            url: "https://github.com/aki-mizu/floresta-swift/releases/download/dev/florestaFFI.xcframework.zip",
            checksum: "8b46ee9cf59c97635f8f32d261eea4c6885637180f6f8f4829a45476b02b0902"
        ),
        // Swift wrapper generated by uniffi-bindgen, placed in Sources/Floresta/ by the build script.
        .target(
            name: "Floresta",
            dependencies: [.target(name: "florestaFFI")],
            path: "Sources/Floresta"
        ),
    ]
)
