// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Floresta",
    platforms: [
        .iOS(.v15),
        .macOS(.v13),
    ],
    products: [
        .library(
            name: "Floresta",
            targets: ["Floresta"]
        ),
    ],
    targets: [
        // XCFramework hosted on GitHub Releases.
        // After pushing a release, set the url to the release asset URL and
        // update the checksum by running:
        //   swift package compute-checksum florestaFFI.xcframework.zip
        .binaryTarget(
            name: "florestaFFI",
            url: "https://github.com/OWNER/floresta-swift/releases/download/0.1.0/florestaFFI.xcframework.zip",
            checksum: "69bc0b6458c306d7ec59f34ee379b2e0cb5cb1754d45484d66c9ddc93c19c588"
        ),
        // Swift wrapper generated by uniffi-bindgen, placed in Sources/Floresta/ by the build script.
        .target(
            name: "Floresta",
            dependencies: [.target(name: "florestaFFI")],
            path: "Sources/Floresta"
        ),
    ]
)
