// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(florestaFFI)
import florestaFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_florestad_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_florestad_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureFlorestadFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A Floresta Bitcoin node instance.
 *
 * Wraps the Floresta daemon and a Tokio runtime. Create with [`Florestad::new`]
 * for defaults or [`Florestad::from_config`] for custom settings. Call
 * [`Florestad::start`] to begin syncing and [`Florestad::stop`] before exit.
 */
public protocol FlorestadProtocol: AnyObject, Sendable {
    
    /**
     * Start the node.
     *
     * Begins syncing the blockchain, serving the Electrum and JSON-RPC
     * interfaces, and watching configured wallets. Returns an error if
     * the data directory is not writable or initialization fails.
     */
    func start() throws 
    
    /**
     * Gracefully stop the node.
     *
     * Waits for all pending operations to finish and flushes data to disk.
     * Always call this before exiting to avoid data corruption.
     */
    func stop() 
    
}
/**
 * A Floresta Bitcoin node instance.
 *
 * Wraps the Floresta daemon and a Tokio runtime. Create with [`Florestad::new`]
 * for defaults or [`Florestad::from_config`] for custom settings. Call
 * [`Florestad::start`] to begin syncing and [`Florestad::stop`] before exit.
 */
open class Florestad: FlorestadProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_florestad_ffi_fn_clone_florestad(self.handle, $0) }
    }
    /**
     * Create a new Floresta node with default configuration.
     *
     * Uses Bitcoin mainnet and the `$HOME/.floresta` data directory.
     * Falls back to the system temp directory if `$HOME` is not set.
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_florestad_ffi_fn_constructor_florestad_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_florestad_ffi_fn_free_florestad(handle, $0) }
    }

    
    /**
     * Create a new Floresta node with the given configuration.
     */
public static func fromConfig(config: Config) -> Florestad  {
    return try!  FfiConverterTypeFlorestad_lift(try! rustCall() {
    uniffi_florestad_ffi_fn_constructor_florestad_from_config(
        FfiConverterTypeConfig_lower(config),$0
    )
})
}
    

    
    /**
     * Start the node.
     *
     * Begins syncing the blockchain, serving the Electrum and JSON-RPC
     * interfaces, and watching configured wallets. Returns an error if
     * the data directory is not writable or initialization fails.
     */
open func start()throws   {try rustCallWithError(FfiConverterTypeFlorestaFfiError_lift) {
    uniffi_florestad_ffi_fn_method_florestad_start(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Gracefully stop the node.
     *
     * Waits for all pending operations to finish and flushes data to disk.
     * Always call this before exiting to avoid data corruption.
     */
open func stop()  {try! rustCall() {
    uniffi_florestad_ffi_fn_method_florestad_stop(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFlorestad: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Florestad

    public static func lift(_ handle: UInt64) throws -> Florestad {
        return Florestad(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Florestad) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Florestad {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Florestad, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlorestad_lift(_ handle: UInt64) throws -> Florestad {
    return try FfiConverterTypeFlorestad.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlorestad_lower(_ value: Florestad) -> UInt64 {
    return FfiConverterTypeFlorestad.lower(value)
}




/**
 * A pre-computed Utreexo accumulator state.
 */
public struct AssumeUtreexoValue: Equatable, Hashable {
    /**
     * The block hash at which this accumulator state is valid.
     */
    public var blockHash: String
    /**
     * The block height at which this accumulator state is valid.
     */
    public var height: UInt32
    /**
     * The Utreexo accumulator roots at this block, as hex strings.
     */
    public var roots: [String]
    /**
     * The number of leaves in the Utreexo accumulator at this block.
     */
    public var leaves: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The block hash at which this accumulator state is valid.
         */blockHash: String, 
        /**
         * The block height at which this accumulator state is valid.
         */height: UInt32, 
        /**
         * The Utreexo accumulator roots at this block, as hex strings.
         */roots: [String], 
        /**
         * The number of leaves in the Utreexo accumulator at this block.
         */leaves: UInt64) {
        self.blockHash = blockHash
        self.height = height
        self.roots = roots
        self.leaves = leaves
    }

    

    
}

#if compiler(>=6)
extension AssumeUtreexoValue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssumeUtreexoValue: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssumeUtreexoValue {
        return
            try AssumeUtreexoValue(
                blockHash: FfiConverterString.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf), 
                roots: FfiConverterSequenceString.read(from: &buf), 
                leaves: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: AssumeUtreexoValue, into buf: inout [UInt8]) {
        FfiConverterString.write(value.blockHash, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterSequenceString.write(value.roots, into: &buf)
        FfiConverterUInt64.write(value.leaves, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssumeUtreexoValue_lift(_ buf: RustBuffer) throws -> AssumeUtreexoValue {
    return try FfiConverterTypeAssumeUtreexoValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssumeUtreexoValue_lower(_ value: AssumeUtreexoValue) -> RustBuffer {
    return FfiConverterTypeAssumeUtreexoValue.lower(value)
}


/**
 * Configuration for the Floresta daemon.
 */
public struct Config: Equatable, Hashable {
    /**
     * Path to the data directory. Must be readable and writable.
     */
    public var datadir: String
    /**
     * The Bitcoin network to run on.
     */
    public var network: Network
    /**
     * Disable DNS seed nodes for peer discovery.
     */
    public var disableDnsSeeds: Bool
    /**
     * Which blocks are assumed to have valid scripts.
     */
    public var assumeValid: AssumeValidArg
    /**
     * SLIP-132-encoded extended public keys to watch.
     */
    public var walletXpub: [String]?
    /**
     * Output descriptors to watch.
     */
    public var walletDescriptor: [String]?
    /**
     * Path to a TOML configuration file.
     */
    public var configFile: String?
    /**
     * SOCKS5 proxy for outgoing connections.
     */
    public var proxy: String?
    /**
     * Whether to build compact block filters.
     */
    public var cfilters: Bool
    /**
     * Block height to start downloading compact filters from.
     */
    public var filtersStartHeight: Int32?
    /**
     * ZMQ server address (requires zmq-server feature).
     */
    public var zmqAddress: String?
    /**
     * Nodes to connect to exclusively.
     */
    public var connect: [String]
    /**
     * JSON-RPC server address (requires json-rpc feature).
     */
    public var jsonRpcAddress: String?
    /**
     * Whether to write logs to stdout.
     */
    public var logToStdout: Bool
    /**
     * Whether to write logs to a file.
     */
    public var logToFile: Bool
    /**
     * Enable assume-utreexo mode.
     */
    public var assumeUtreexo: Bool
    /**
     * Enable debug logging.
     */
    public var debug: Bool
    /**
     * User agent string advertised to peers.
     */
    public var userAgent: String
    /**
     * Custom Utreexo accumulator state for assume-utreexo.
     */
    public var assumeutreexoValue: AssumeUtreexoValue?
    /**
     * Electrum server address.
     */
    public var electrumAddress: String?
    /**
     * Whether to enable the Electrum TLS server.
     */
    public var enableElectrumTls: Bool
    /**
     * Electrum TLS server address.
     */
    public var electrumAddressTls: String?
    /**
     * Path to the TLS private key file.
     */
    public var tlsKeyPath: String?
    /**
     * Path to the TLS certificate file.
     */
    public var tlsCertPath: String?
    /**
     * Whether to generate a self-signed TLS certificate.
     */
    public var generateCert: Bool
    /**
     * Whether to allow v1 transport fallback.
     */
    public var allowV1Fallback: Bool
    /**
     * Whether to backfill skipped blocks.
     */
    public var backfill: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Path to the data directory. Must be readable and writable.
         */datadir: String, 
        /**
         * The Bitcoin network to run on.
         */network: Network, 
        /**
         * Disable DNS seed nodes for peer discovery.
         */disableDnsSeeds: Bool = false, 
        /**
         * Which blocks are assumed to have valid scripts.
         */assumeValid: AssumeValidArg, 
        /**
         * SLIP-132-encoded extended public keys to watch.
         */walletXpub: [String]? = nil, 
        /**
         * Output descriptors to watch.
         */walletDescriptor: [String]? = nil, 
        /**
         * Path to a TOML configuration file.
         */configFile: String? = nil, 
        /**
         * SOCKS5 proxy for outgoing connections.
         */proxy: String? = nil, 
        /**
         * Whether to build compact block filters.
         */cfilters: Bool = false, 
        /**
         * Block height to start downloading compact filters from.
         */filtersStartHeight: Int32? = nil, 
        /**
         * ZMQ server address (requires zmq-server feature).
         */zmqAddress: String? = nil, 
        /**
         * Nodes to connect to exclusively.
         */connect: [String] = [], 
        /**
         * JSON-RPC server address (requires json-rpc feature).
         */jsonRpcAddress: String? = nil, 
        /**
         * Whether to write logs to stdout.
         */logToStdout: Bool = false, 
        /**
         * Whether to write logs to a file.
         */logToFile: Bool = false, 
        /**
         * Enable assume-utreexo mode.
         */assumeUtreexo: Bool = false, 
        /**
         * Enable debug logging.
         */debug: Bool = false, 
        /**
         * User agent string advertised to peers.
         */userAgent: String = "", 
        /**
         * Custom Utreexo accumulator state for assume-utreexo.
         */assumeutreexoValue: AssumeUtreexoValue? = nil, 
        /**
         * Electrum server address.
         */electrumAddress: String? = nil, 
        /**
         * Whether to enable the Electrum TLS server.
         */enableElectrumTls: Bool = false, 
        /**
         * Electrum TLS server address.
         */electrumAddressTls: String? = nil, 
        /**
         * Path to the TLS private key file.
         */tlsKeyPath: String? = nil, 
        /**
         * Path to the TLS certificate file.
         */tlsCertPath: String? = nil, 
        /**
         * Whether to generate a self-signed TLS certificate.
         */generateCert: Bool = false, 
        /**
         * Whether to allow v1 transport fallback.
         */allowV1Fallback: Bool = false, 
        /**
         * Whether to backfill skipped blocks.
         */backfill: Bool = false) {
        self.datadir = datadir
        self.network = network
        self.disableDnsSeeds = disableDnsSeeds
        self.assumeValid = assumeValid
        self.walletXpub = walletXpub
        self.walletDescriptor = walletDescriptor
        self.configFile = configFile
        self.proxy = proxy
        self.cfilters = cfilters
        self.filtersStartHeight = filtersStartHeight
        self.zmqAddress = zmqAddress
        self.connect = connect
        self.jsonRpcAddress = jsonRpcAddress
        self.logToStdout = logToStdout
        self.logToFile = logToFile
        self.assumeUtreexo = assumeUtreexo
        self.debug = debug
        self.userAgent = userAgent
        self.assumeutreexoValue = assumeutreexoValue
        self.electrumAddress = electrumAddress
        self.enableElectrumTls = enableElectrumTls
        self.electrumAddressTls = electrumAddressTls
        self.tlsKeyPath = tlsKeyPath
        self.tlsCertPath = tlsCertPath
        self.generateCert = generateCert
        self.allowV1Fallback = allowV1Fallback
        self.backfill = backfill
    }

    

    
}

#if compiler(>=6)
extension Config: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Config {
        return
            try Config(
                datadir: FfiConverterString.read(from: &buf), 
                network: FfiConverterTypeNetwork.read(from: &buf), 
                disableDnsSeeds: FfiConverterBool.read(from: &buf), 
                assumeValid: FfiConverterTypeAssumeValidArg.read(from: &buf), 
                walletXpub: FfiConverterOptionSequenceString.read(from: &buf), 
                walletDescriptor: FfiConverterOptionSequenceString.read(from: &buf), 
                configFile: FfiConverterOptionString.read(from: &buf), 
                proxy: FfiConverterOptionString.read(from: &buf), 
                cfilters: FfiConverterBool.read(from: &buf), 
                filtersStartHeight: FfiConverterOptionInt32.read(from: &buf), 
                zmqAddress: FfiConverterOptionString.read(from: &buf), 
                connect: FfiConverterSequenceString.read(from: &buf), 
                jsonRpcAddress: FfiConverterOptionString.read(from: &buf), 
                logToStdout: FfiConverterBool.read(from: &buf), 
                logToFile: FfiConverterBool.read(from: &buf), 
                assumeUtreexo: FfiConverterBool.read(from: &buf), 
                debug: FfiConverterBool.read(from: &buf), 
                userAgent: FfiConverterString.read(from: &buf), 
                assumeutreexoValue: FfiConverterOptionTypeAssumeUtreexoValue.read(from: &buf), 
                electrumAddress: FfiConverterOptionString.read(from: &buf), 
                enableElectrumTls: FfiConverterBool.read(from: &buf), 
                electrumAddressTls: FfiConverterOptionString.read(from: &buf), 
                tlsKeyPath: FfiConverterOptionString.read(from: &buf), 
                tlsCertPath: FfiConverterOptionString.read(from: &buf), 
                generateCert: FfiConverterBool.read(from: &buf), 
                allowV1Fallback: FfiConverterBool.read(from: &buf), 
                backfill: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Config, into buf: inout [UInt8]) {
        FfiConverterString.write(value.datadir, into: &buf)
        FfiConverterTypeNetwork.write(value.network, into: &buf)
        FfiConverterBool.write(value.disableDnsSeeds, into: &buf)
        FfiConverterTypeAssumeValidArg.write(value.assumeValid, into: &buf)
        FfiConverterOptionSequenceString.write(value.walletXpub, into: &buf)
        FfiConverterOptionSequenceString.write(value.walletDescriptor, into: &buf)
        FfiConverterOptionString.write(value.configFile, into: &buf)
        FfiConverterOptionString.write(value.proxy, into: &buf)
        FfiConverterBool.write(value.cfilters, into: &buf)
        FfiConverterOptionInt32.write(value.filtersStartHeight, into: &buf)
        FfiConverterOptionString.write(value.zmqAddress, into: &buf)
        FfiConverterSequenceString.write(value.connect, into: &buf)
        FfiConverterOptionString.write(value.jsonRpcAddress, into: &buf)
        FfiConverterBool.write(value.logToStdout, into: &buf)
        FfiConverterBool.write(value.logToFile, into: &buf)
        FfiConverterBool.write(value.assumeUtreexo, into: &buf)
        FfiConverterBool.write(value.debug, into: &buf)
        FfiConverterString.write(value.userAgent, into: &buf)
        FfiConverterOptionTypeAssumeUtreexoValue.write(value.assumeutreexoValue, into: &buf)
        FfiConverterOptionString.write(value.electrumAddress, into: &buf)
        FfiConverterBool.write(value.enableElectrumTls, into: &buf)
        FfiConverterOptionString.write(value.electrumAddressTls, into: &buf)
        FfiConverterOptionString.write(value.tlsKeyPath, into: &buf)
        FfiConverterOptionString.write(value.tlsCertPath, into: &buf)
        FfiConverterBool.write(value.generateCert, into: &buf)
        FfiConverterBool.write(value.allowV1Fallback, into: &buf)
        FfiConverterBool.write(value.backfill, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfig_lift(_ buf: RustBuffer) throws -> Config {
    return try FfiConverterTypeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfig_lower(_ value: Config) -> RustBuffer {
    return FfiConverterTypeConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Configures the assume-valid behavior for script validation.
 */

public enum AssumeValidArg: Equatable, Hashable {
    
    /**
     * Validate all scripts from genesis.
     */
    case disabled
    /**
     * Use Floresta's hard-coded block hash.
     */
    case hardcoded
    /**
     * Use a user-provided block hash (64-character hex string).
     */
    case userInput(blockHash: String
    )





}

#if compiler(>=6)
extension AssumeValidArg: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssumeValidArg: FfiConverterRustBuffer {
    typealias SwiftType = AssumeValidArg

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssumeValidArg {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disabled
        
        case 2: return .hardcoded
        
        case 3: return .userInput(blockHash: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AssumeValidArg, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disabled:
            writeInt(&buf, Int32(1))
        
        
        case .hardcoded:
            writeInt(&buf, Int32(2))
        
        
        case let .userInput(blockHash):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(blockHash, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssumeValidArg_lift(_ buf: RustBuffer) throws -> AssumeValidArg {
    return try FfiConverterTypeAssumeValidArg.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssumeValidArg_lower(_ value: AssumeValidArg) -> RustBuffer {
    return FfiConverterTypeAssumeValidArg.lower(value)
}



/**
 * Error returned by the Floresta FFI layer.
 */
public enum FlorestaFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The daemon failed to start, with an error message.
     */
    case StartError(details: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FlorestaFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFlorestaFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FlorestaFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FlorestaFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .StartError(
            details: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FlorestaFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .StartError(details):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(details, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlorestaFfiError_lift(_ buf: RustBuffer) throws -> FlorestaFfiError {
    return try FfiConverterTypeFlorestaFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlorestaFfiError_lower(_ value: FlorestaFfiError) -> RustBuffer {
    return FfiConverterTypeFlorestaFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The Bitcoin network to run on.
 */

public enum Network: Equatable, Hashable {
    
    /**
     * Bitcoin mainnet.
     */
    case bitcoin
    /**
     * Bitcoin signet.
     */
    case signet
    /**
     * Bitcoin testnet.
     */
    case testnet
    /**
     * Bitcoin regtest.
     */
    case regtest
    /**
     * Bitcoin testnet4.
     */
    case testnet4





}

#if compiler(>=6)
extension Network: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNetwork: FfiConverterRustBuffer {
    typealias SwiftType = Network

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Network {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bitcoin
        
        case 2: return .signet
        
        case 3: return .testnet
        
        case 4: return .regtest
        
        case 5: return .testnet4
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Network, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bitcoin:
            writeInt(&buf, Int32(1))
        
        
        case .signet:
            writeInt(&buf, Int32(2))
        
        
        case .testnet:
            writeInt(&buf, Int32(3))
        
        
        case .regtest:
            writeInt(&buf, Int32(4))
        
        
        case .testnet4:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetwork_lift(_ buf: RustBuffer) throws -> Network {
    return try FfiConverterTypeNetwork.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetwork_lower(_ value: Network) -> RustBuffer {
    return FfiConverterTypeNetwork.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAssumeUtreexoValue: FfiConverterRustBuffer {
    typealias SwiftType = AssumeUtreexoValue?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAssumeUtreexoValue.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAssumeUtreexoValue.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_florestad_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_florestad_ffi_checksum_method_florestad_start() != 46712) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_florestad_ffi_checksum_method_florestad_stop() != 14010) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_florestad_ffi_checksum_constructor_florestad_from_config() != 1006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_florestad_ffi_checksum_constructor_florestad_new() != 15358) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureFlorestadFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all